mbdebate_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin
    path('anything-but-admin/', admin.site.urls),

    # User authentification
    path('accounts/', include('allauth.urls')),


    # apps    
    path('', include('pages.urls')),
    path('accounts/', include('users.urls')), 
    path('tournaments/', include('tournaments.urls')),
    path('posts/', include('posts.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, CoachesPageView, TemporaryTournament

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('coaches/', CoachesPageView.as_view(), name='coaches'),
    path('blairbebate/', TemporaryTournament.as_view(), name='temporary'),
]

tournaments/models.py
from django.db import models


from django.contrib.auth import get_user_model
from django.conf import settings
from django.urls import reverse 

from users.models import CustomUser

class Tournament(models.Model):
    name = models.CharField(max_length=255)
    date = models.CharField(max_length=10, null=True)
    enddate = models.CharField(max_length=10, null=True)
    cost = models.FloatField(null=True)
    link = models.CharField(max_length=50, null=True)

    location = models.CharField(max_length=50, null=True)
    
    is_payment_due = models.BooleanField(default=False)
    

    
    slug = models.SlugField(null=False, unique=True, default=None)

    users = models.ManyToManyField(CustomUser,blank=True) # through payment

    


    def show_users(self):
        return ', '.join([a.email for a in self.users.all()])

    @classmethod
    def register(cls, user, tournament):
        tournament.users.add(user)

    @classmethod
    def unregister(cls, user, tournament):
        tournament.users.remove(user)

  

    def __str__(self):
        return self.name

   

# class Payment(models.Model):
#     total_cost = models.FloatField(null=True)
    
#     transportation_cost = models.FloatField(null=True)

#     lodging_cost = models.FloatField(null=True)

#     registration_fee = models.FloatField(null=True)

templates/_base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}MB Debate{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- flavicon -->
  <link rel="shortcut icon" type="image/png" href="{% static '/images/flavicon.png' %}" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Personal CSS -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <nav{% if request.path == '/'%} class="navbar navbar-expand-md navbar-dark bg-dark" {% else %} class="navbar navbar-expand-md navbar-dark bg-dark mb-4" {% endif %}>
      <a href="{% url 'home' %}" class="navbar-brand font-weight-normal">MB Debate</a>
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item"><a class = "nav-link" href="#">Tournament List</a></li> -->
        {% url 'coaches' as coaches %}
        {% url 'about' as about %}
        {% url 'post_list' as posts %}
        <li {% if 'tournaments' in request.path %} class="nav-item dropdown active" {% else %} class="nav-item dropdown" {% endif %}>
          
         
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Tournaments
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'list' %}">List</a>
            <a class="dropdown-item" href="{% url 'fullregister' %}">Registration</a>
            <a class="dropdown-item" href="#">History</a>
          </div>
        </li>
        <!-- url links for if loops -->
        
        <li {% if request.path == coaches %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'coaches' %}">Coaches</a></li>
        <li {% if request.path == about %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'about' %}">About</a></li>
        <li {% if request.path == posts %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'post_list' %}">Forum</a></li>
      </ul>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                                data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                {{ user.first_name }} {{ user.last_name }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <a class="dropdown-item" href=#>Change password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log In</a>
                        <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
                    </form>
                {% endif %}
            </div>
    </nav>
  </header>
  
  <div class="wrapper">
    {% block home %}
    {% endblock home %}
    {% url 'home' as home %}
      <div {% if request.path == home or request.path == about %}class="container mb-0" {% else %} class="container mb-4" {% endif %}>
          {% block content %}
          {% endblock content %}
      </div>
      <div class="push"></div>
      </div>
      <footer id="footer" class="py-1 bg-dark text-white-50">
        <div class="container text-center">
          <small>&copy;2020 Pulsar Academy. All Rights Reserved.</small>
        </div>
      </footer>
  
  <!-- JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/about.html
{% extends '_base.html' %}

{% block title%}About{% endblock title %}

{% block content %}

<h1>About Page</h1>
<br>
<p class="lead">We are Montgomery Blair Debate, a student-managed debate team from Maryland. We participate in the National Circuit in PF, and 
    we have had multiple TOC-qualifying teams. Our team captains for next year are Iris Gupta and Alex Jiang. Our supreme leader is Eli Qian, even
    though he eats oranges with the peel on. Thank you for checking us out!

    Images and other stuff will be added eventually so don't judge this page quite yet.
</p>

{% endblock content %}

templates/blairbebate.html
{% extends '_base.html' %}
{% load static %}
{% load icon %}

{% block title %}Blair Bebate Site{% endblock title %}

{% block content %}
<h1>Welcome to the Blair Bebate Tournament</h1>

<br>
<p class="text-center"><a class="btn btn-outline-info" href="https://www.tabroom.com/index/tourn/index.mhtml?tourn_id=16482">Tabroom</a></p>
<br>
<div class="card-deck">
    <div class="card">
      <div class="card-header">Room 1</div>
        <div class="card-body">
          
          <p class="card-text">Zoom link: <a href="https://us02web.zoom.us/j/87669693966?pwd=c1p3a0hEV3pDNnYzQ3ZCeWNIYVd6dz09">here</a></p>
          {% icon 'heart' %}
          {% icon 'heart' %}
          {% icon 'heart' %}
          {% icon 'heart' %}
          {% icon 'heart' %}
          {% icon 'heart' %}
          {% icon 'heart' %}
        </div>
      </div>
      <div class="card">
        <div class="card-header">Room 2</div>
        <div class="card-body">
          
          <p class="card-text">Zoom link: <a href="https://us02web.zoom.us/j/84128682452?pwd=emduOExjOE52cU1HMk1YaWV0cEx0QT09">here</a></p>
          {% icon 'truck' %}
          {% icon 'truck' %}
          {% icon 'truck' %}
          {% icon 'truck' %}
          {% icon 'truck' %}
          {% icon 'truck' %}
          {% icon 'truck' %}
        </div>
      </div>
      <div class="card">
        <div class="card-header">Room 3</div>
        <div class="card-body">
         
          <p class="card-text">Zoom link: <a href="https://us02web.zoom.us/j/88953130945?pwd=L0VmL3MvWHRiLytPc1dTa1lOaVZ3dz09">here</a></p>
          {% icon 'coffee' %}
          {% icon 'coffee' %}
          {% icon 'coffee' %}
          {% icon 'coffee' %}
          {% icon 'coffee' %}
        {% icon 'coffee' %}
        {% icon 'coffee' %}
          
          
        </div>
      </div>
          
</div>
<br><br>
<img src="{% static 'images/dedede.png' %}" height="500px">
{% endblock content %}

templates/coaches.html
{% extends '_base.html' %}
{% load static %}

{% block title%}Coaches{% endblock title %}

{% block content %}

<h1>Meet Our Coaches</h1>
<br>
<div class="card-deck">
    <div class="card">
      <img class="card-img-top" src="{% static 'images/bengoldberg.jpg' %}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Ben Goldberg</h5>
        <p class="card-text">Ben is a rising junior at Cornell University. He debated for Half Hollow Hills High School, where he qualified
            to the TOC in his senior year. Ben enjoys watching Netflix, sleeping, and listening to classical rock. He has expressed his distaste
            towards quarantine. When asked about his feelings towards Mongtomery Blair, he said, "Blair is the best team on the planet and I love coaching them." 
            He also clearly expressed his favoritism for the best debater on the team, Eric Chen. 

        </p>
        <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
      </div>
    </div>
    <div class="card">
      <img class="card-img-top" src="{% static 'images/davidkinane.jpg' %}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">David Kinane</h5>
        <p class="card-text">David is a rising sophomore at the University of Michigan. He debated for Unionville High School,
            and qualified to the TOC with a career total of 6 bids. He broke to eliminations at the TOC in his senior year, where he 
            also won a speaker award. He enjoys listening to music, skateboarding, and surfing. In his free time, he cooks pineapples for breakfast
            and boils ice cubes in the hot tub.
        </p>
        <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
      </div>
    </div>
    
    
    
   
  </div>
  <br>
<br>

{% endblock content %}

templates/home.html
<!-- templates/home.html -->

{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block home %}

<div class="jumbotron jumbotron-fluid text-white" style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.6) 0%,rgba(0,0,0,0.6) 100%), url('{% static 'images/background.png' %}')">
    <div class="container">
        <h1 class="display-1">Welcome to Montgomery Blair Debate</h1>
        
        <!-- <p class="lead">All your information is here!</p> -->
        <!-- <hr class="my-4"> -->
        {% if user.is_authenticated %}
            <p class="lead">Hi {{ user.email }}!</p>
            <a class="btn btn-primary" href="{% url 'account_logout' %}">Log Out</a>
        {% else %}
            <p class="lead">You are not logged in</p>
            <p class="lead">
                <a href="{% url 'account_login' %}">Log In</a>
                or sign up <a href="{% url 'account_signup' %}">here</a>
            </p>

        {% endif %}
        <!-- <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> -->
    </div>

</div>



{% endblock home %}


 

templates/profile.html
{% extends '_base.html' %}

{% block title%}Profile{% endblock title %}

{% block content %}

<h1>Profile</h1>
{% if user.is_authenticated %}
<p>Hi {{ user.email }}</p>



{% if request.user.tournament_set.all %}
<p class="lead">Registered Tournaments:</p>
{% for tournament in request.user.tournament_set.all %}
    <div class="card">
        <div class="card-header">
            <span class="font-weight-bold"><a href="{% url 'detail' tournament.slug %}">{{ tournament.name }}</a></span> &middot;
            <span class="text-muted">{{ tournament.date }}</span>
    
        </div>
    
        <div class="card-body">
            <p>Registration fee: ${{ tournament.cost }}</p>
    
            
            <!-- Comments added here -->     
        </div>
        <!-- <div class="card-footer">
        <small><a href="{% url 'detail' tournament.slug %}">View details</a></small>
        </div> -->
    </div>
    <br/>
{% endfor %}
{% else %}
<p class="lead">You aren't signed up for any tournaments. Sign up <a href="{% url 'fullregister' %}">here</a>.</p>
{% endif %}

{% else %}
<h1>You are not logged in.</h1>
<p><a href="{% url 'account_login' %}">Login</a></p>
{% endif %}

{% endblock content %}

templates/tournament_detail.html
<!-- templates/article_detail.html -->

{% extends '_base.html' %}

{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
    
    <h1>{{ object.name }}</h1>
    <p>Cost: ${{ object.cost }}</p>
    <p>Link to website: <a href={{ object.link }}>Link</a></p>
    

    {% if request.user in object.users.all %}
        <p><a href="{% url 'unregister' object.slug %}">Unregister</a></p> 
    {% else %}
        <p><a href="{% url 'register' object.slug %}">Register</a></p>
    {% endif %}
    <br/>

    {% if object.users.all %}
    <p class="lead">People signed up:</p>
    <ul>
    {% for user in object.users.all %}
        <li>{{ user }}</li>
    {% endfor %}
    </ul>
    {% else %}
    <p class="lead">No one has signed up yet.</p>
    {% endif %}
{% endblock content %}

templates/tournament_full_registration.html
<!-- templates/article_detail.html -->

{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Registration Form{% endblock title %}

{% block content %}
    <h1>Registration</h1>
    <!-- {% if user.is_authenticated %} -->
    <p class="lead">Remember, every tournament you sign up for, you sign up your partner as well. Make sure you check with them beforehand. To see the list of tournament in more detail
        go to <a href="{% url 'list' %}">tournament list</a>.
    </p>
    <p class="text-muted">You can also register tournaments individually by clicking on a specific tournament in the lists page.</p>

    <br/>
    <div class="card">
        <div class="card-body">
            <form method="post" id="mcform">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
    </div>
    </div>

    <!-- {% else %}
    <p class="lead">You are not logged in.</p>
    <p>Log in <a href="{% url 'account_login' %}">here</a>.</p>
    {% endif %} -->
    
{% endblock content %}

templates/tournament_list.html
{% extends '_base.html' %}

{% block title%}Tournament List{% endblock title %}

{% block content %}

<div class="card text-center">
  
   <div class="card-body">
     <h5 class="card-title">Registration Has Begun!</h5>
     <p class="card-text">You can register by filling the form, or clicking the individual tournaments and register individually.</p>
     <a href="{% url 'fullregister' %}" class="btn btn-primary">Register</a>
     
   </div>
 </div>
 <br/>
     
{% for tournament in object_list %}

<div class="card">
   <div class="card-header">
       <span class="font-weight-bold"><a href="{% url 'detail' tournament.slug %}">{{ tournament.name }}</a></span> &middot;
       <span class="text-muted">{{ tournament.date }} - {{ tournament.enddate }}</span>

   </div>

   <div class="card-body">
      <p>Location: {{ tournament.location }}</p>
       <p>Registration fee: ${{ tournament.cost }}</p>
       

       
       <!-- Comments added here -->     
   </div>
   <!-- <div class="card-footer">
      <small><a href="{% url 'detail' tournament.slug %}">View details</a></small>
   </div> -->
</div>
<br />

{% endfor %}

{% endblock content %}

templates/tournament_registration.html
{% extends '_base.html' %}

{% block title%}Tournament Register{% endblock title %}


{% block content %}
<h1>Register for {{ object.name }}</h1>

{% if user.is_authenticated %}
<p class="lead">You are registering for {{ object.name }}. You will also sign up your partner.</p>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-success" type="submit">Register</button>
</form>
{% else %}
    <p class="lead">You are not logged in.</p>
    <p>Log in <a href="{% url 'account_login' %}">here</a>.</p>
{% endif %}

{% endblock content %}

templates/tournament_unregister.html
{% extends '_base.html' %}

{% block title%}Unregister{% endblock title %}

{% block content %}

<h1>Unregister from {{ object.name }}</h1>
<br/>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">Unregister</button>
</form>
     

{% endblock content %}